### ISSUE TITLE
One line missing with Crunchbang Distro

### ISSUE THREAD

**Issue by HorlogeSkynet** [djmelik/archey#32]
**Traceback (most recent call last):
  File "/usr/bin/archey", line 304, in <module>
    func()
  File "/usr/bin/archey", line 184, in distro_display
    output('OS', distro)
UnboundLocalError: local variable 'distro' referenced before assignment**

We have to add `distro = 'CrunchBang %s %s' % (release, arch)` manually at line _180_.

**Comment by HorlogeSkynet** [comment]
CrunchBang should be handled now here 8ff46ed54ede3ec33c1a782b53763645394e4179
