### ISSUE TITLE
Error with some hard drive names

### ISSUE THREAD

**Issue by HorlogeSkynet** [djmelik/archey#34]
**Traceback (most recent call last):
  File "/usr/bin/archey", line 305, in <module>
    func()
  File "/usr/bin/archey", line 289, in disk_display
    usedpercent = float(re.sub("[A-Z]", "", used)) / float(re.sub("[A-Z]", "", size)) \* 100
ValueError: invalid literal for float(): 1,6**

There is a problem if a hard drive with some special characters in its name is plugged in.
Thank you !

EDIT: It's not name-related, but same issue about the disk usage parsing (sorry for the duplicate then).

**Comment by HorlogeSkynet** [comment]
Fix' here 3a920d7b8cc7b9252fe67239334ad771da4e598a
