### ISSUE TITLE
Missing support for simfs/tempfs. Poor VPS support.

### ISSUE THREAD

**Issue by Niyusha** [djmelik/archey#39]
I created a fix and a pull request here: [https://github.com/djmelik/archey/pull/38](url)

**How to fix since my branch hasn't been merged yet:**
If you get the following error when trying to run Archey (especially if you are doing it in a VPS):

`Traceback (most recent call last):
  File "/usr/bin/archey", line 304, in <module>
    func()
  File "/usr/bin/archey", line 285, in disk_display
    total = p1.splitlines()[-1]
IndexError: list index out of range`

Then chances are it didn't worse because of missing support for SimFs/TempFs. To fix this just edit this line in /usr/bin/archey

`p1 = Popen(['df', '-Tlh', '--total', '-t', 'ext4', '-t', 'ext3', '-t', 'ext2', '-t', 'reiserfs', '-t', 'jfs', '-t', 'ntfs', '-t', 'fat32', '-t', 'btrfs', '-t', 'fuseblk', '-t', 'xfs'], stdout=PIPE).communicate()[0].decode("Utf-8")`

to read 

`p1 = Popen(['df', '-Tlh', '--total', '-t', 'ext4', '-t', 'ext3', '-t', 'ext2', '-t', 'reiserfs', '-t', 'jfs', '-t', 'ntfs', '-t', 'fat32', '-t', 'btrfs', '-t', 'fuseblk', '-t', 'simfs', '-t', 'tempfs'], stdout=PIPE).communicate()[0]`

Save and re run the archey command. If it works congrats you fixed Archey to work for you! If it still doesn't work please reply with the error outputted.

**Comment by HelenaKitty** [comment]
My fork of archey fixes that issue! I was required to run archey in a virtual environment, however the software was missing support for simfs/tempfs, but my fork has that support.
https://github.com/HelenaKitty/KaffeSI
