### ISSUE TITLE
RAM_display issue

### ISSUE THREAD

**Issue by Davvvid12345** [djmelik/archey#42]
RAM_DISPLAY ISSUE on ubuntu 16.04.
Output from the terminal:

**Traceback (most recent call last):
  File "/usr/bin/archey", line 304, in <module>
    func()
  File "/usr/bin/archey", line 140, in ram_display
    used = int(ram[2]) - int(ram[5]) - int(ram[6])
IndexError: list index out of range**

**Comment by HorlogeSkynet** [comment]
Everything should be fixed here: https://github.com/HorlogeSkynet/Archey4
