### ISSUE TITLE
Error on Ubuntu 12.04

### ISSUE THREAD

**Issue by deshack** [djmelik/archey#7]
Package version: 0.2.8
Operating System: Ubuntu 12.04 LTS
Python version: 2.7.3
Error message (when launching "archey" command):

Traceback (most recent call last):
   File "/usr/bin/archey", line 304, in <module>
      func()
   File "/usr/bin/archey", line 288, in disk_display
      usedpercent = float(re.sub("[A-Z]", "", used)) / float(re.sub("[A-Z]", "", size)) \* 100
ValueError: invalid literal for float(): 4,9

**Comment by xnosx** [comment]
@jherazob your tip works for me, thanks!
